2023-04-05 01:25:16,205 INFO    MainThread:26245 [wandb_setup.py:_flush():76] Configure stats pid to 26245
2023-04-05 01:25:16,205 INFO    MainThread:26245 [wandb_setup.py:_flush():76] Loading settings from /u8/c/evanpan/.config/wandb/settings
2023-04-05 01:25:16,205 INFO    MainThread:26245 [wandb_setup.py:_flush():76] Loading settings from /nfs/artemis.dgpsrv/ondemand27/evanpan/Gaze_project/training/wandb/settings
2023-04-05 01:25:16,205 INFO    MainThread:26245 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-04-05 01:25:16,205 INFO    MainThread:26245 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-04-05 01:25:16,205 INFO    MainThread:26245 [wandb_init.py:_log_setup():506] Logging user logs to /nfs/artemis.dgpsrv/ondemand27/evanpan/Gaze_project/training/wandb/run-20230405_012516-n7k0nhxh/logs/debug.log
2023-04-05 01:25:16,205 INFO    MainThread:26245 [wandb_init.py:_log_setup():507] Logging internal logs to /nfs/artemis.dgpsrv/ondemand27/evanpan/Gaze_project/training/wandb/run-20230405_012516-n7k0nhxh/logs/debug-internal.log
2023-04-05 01:25:16,205 INFO    MainThread:26245 [wandb_init.py:init():546] calling init triggers
2023-04-05 01:25:16,205 INFO    MainThread:26245 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {'win_length': 10, 'stride_length': 5, 'model_type': 'transformer', 'num_layers': 3, 'input_dims': 1674, 'input_layer_out': 256, 'frames_ahead': 0, 'frames_behind': 0, 'lstm_layer_num': 1, 'lstm_feature_size': 256, 'lstm_output_feature_size': 256, 'output_layer_1_hidden': 64, 'output_layer_2_hidden': 64, 'output_layer_3_hidden': 1, 'wandb': True, 'load_model': False, 'checkpoint_name': '', 'checkpoint_path': '', 'batch_size': 256, 'learning_rate': 0.1, 'dropout': 0.2, 'epochs': 200, 'device': 'gpu', 'early_stopping': 10}
2023-04-05 01:25:16,205 INFO    MainThread:26245 [wandb_init.py:init():568] re-initializing run, found existing run on stack: 1x4822nw
2023-04-05 01:25:16,207 INFO    MainThread:26245 [wandb_run.py:_finish():1854] finishing run gaze_prediction_team/gaze_prediction/1x4822nw
2023-04-05 01:25:16,207 INFO    MainThread:26245 [jupyter.py:save_history():445] not saving jupyter history
2023-04-05 01:25:16,207 INFO    MainThread:26245 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-04-05 01:25:16,207 INFO    MainThread:26245 [wandb_init.py:_jupyter_teardown():434] cleaning up jupyter logic
2023-04-05 01:25:16,207 INFO    MainThread:26245 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-04-05 01:25:16,207 INFO    MainThread:26245 [wandb_run.py:_restore():2066] restore
2023-04-05 01:25:16,208 INFO    MainThread:26245 [wandb_run.py:_restore():2072] restore done
2023-04-05 01:25:20,481 INFO    MainThread:26245 [wandb_run.py:_footer_history_summary_info():3422] rendering history
2023-04-05 01:25:20,481 INFO    MainThread:26245 [wandb_run.py:_footer_history_summary_info():3454] rendering summary
2023-04-05 01:25:20,489 INFO    MainThread:26245 [wandb_run.py:_footer_sync_info():3380] logging synced files
2023-04-05 01:25:20,495 INFO    MainThread:26245 [wandb_init.py:init():602] starting backend
2023-04-05 01:25:20,496 INFO    MainThread:26245 [wandb_init.py:init():606] setting up manager
2023-04-05 01:25:20,497 INFO    MainThread:26245 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: fork
2023-04-05 01:25:20,498 INFO    MainThread:26245 [wandb_init.py:init():613] backend started and connected
2023-04-05 01:25:20,504 INFO    MainThread:26245 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2023-04-05 01:25:20,504 INFO    MainThread:26245 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-04-05 01:25:20,504 INFO    MainThread:26245 [wandb_init.py:init():701] updated telemetry
2023-04-05 01:25:20,575 INFO    MainThread:26245 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
2023-04-05 01:25:21,329 WARNING MainThread:26245 [wandb_init.py:init():1165] interrupted
Traceback (most recent call last):
  File "/scratch/ondemand27/evanpan/conda_env/.conda/envs/jaligaze/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1144, in init
    run = wi.init()
  File "/scratch/ondemand27/evanpan/conda_env/.conda/envs/jaligaze/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 744, in init
    result = run_init_handle.wait(
  File "/scratch/ondemand27/evanpan/conda_env/.conda/envs/jaligaze/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/scratch/ondemand27/evanpan/conda_env/.conda/envs/jaligaze/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/scratch/ondemand27/evanpan/conda_env/.conda/envs/jaligaze/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/scratch/ondemand27/evanpan/conda_env/.conda/envs/jaligaze/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/scratch/ondemand27/evanpan/conda_env/.conda/envs/jaligaze/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
